-- Statuts de compte enrichis (Inactif, Absence justifiée, Congé administratif, Décédé).
ALTER TABLE `User` MODIFY `status` ENUM('ACTIVE','LOA','INACTIVE','EXCUSED_ABSENCE','ADMIN_LEAVE','SUSPENDED','DISCHARGED','DECEASED') NOT NULL DEFAULT 'ACTIVE';
UPDATE `User` SET `status` = 'ADMIN_LEAVE' WHERE `status` = 'LOA';
ALTER TABLE `User` MODIFY `status` ENUM('ACTIVE','INACTIVE','EXCUSED_ABSENCE','ADMIN_LEAVE','SUSPENDED','DISCHARGED','DECEASED') NOT NULL DEFAULT 'ACTIVE';
